spring.application.name=StackerRat
spring.main.banner-mode=off
logging.level.root=warn
spring.datasource.url=jdbc:postgresql://${POST_HOST:localhost}:${POST_PORT:5432}/${POST_DB:stalkerrat}
spring.datasource.username=${POST_USER_NAME:postgres}
spring.datasource.password=${POST_PASSWORD:ahmed811}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.web=DEBUG


application.security.jwt.secret-key=${JWT_SECRET_KEY:f0K9Jv1QXkWl2N8m3p5sTz9g6YhLdBqM7XoV4rZPUCY=}
application.security.jwt.expiration=86400000